config/routes.rb
Rails.application.routes.draw do
  # namespace :c1 do
  root to: 'cruds#index'
  resources :cruds
  # end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crud.rb
class Crud < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cruds_controller.rb
class CrudsController < ApplicationController
	def index
		@cruds = Crud.all
		# render json: @cruds, status: :ok
	end

	def create
		@crud = Crud.new(crud_params)
		@crud.save
		# render json: @crud, status: :created
	end

	def new
		@crud = Crud.new()
	end

	def destroy
		@crud = Crud.find(params[:id])
		 @crud.destroy
	end

	def show
		@crud = Crud.find(params[:id])
	end

	def update
		@crud = Crud.find(params[:id])
		@crud.update(crud_params)
	end

	def edit
		@crud = Crud.find(params[:id])
	end

	private

	def crud_params
		params.require(:crud).permit(:f_name, :l_name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cruds_helper.rb
module CrudsHelper
end

app/views/cruds/edit.html.erb
<h1> Edit </h1>

<p> First Name : <%= @crud.f_name %></p>
<p> Last Name : <%= @crud.l_name %></p>

<%= form_with(model: @crud, class: "shadow p-3 mb-3 bg-info rounded", local: true) do |f| %>
  <div class="row mb-3">
    <%= f.label :FirtName, class: "col-sm-2 col-form-label text-light" %>
    <div class="col-sm-10">
      <%= f.text_field :f_name, class: "form-control shadow rounded" %>
    </div>
  </div>

  <div class="row mb-3">
    <%= f.label :LastName, class: "col-sm-2 col-form-label text-light" %>
    <div class="col-sm-10">
      <%= f.text_field :l_name, rows: 10, class: "form-control shadow rounded" %>
    </div>
  </div>

  <div class="d-flex justify-content-center">
    <%= f.submit class: "btn btn-outline-light btn-sm" %>
  </div>

<% end %>
</div>

app/views/cruds/index.html.erb
<h1> Index </h1>

<% @cruds.each do |crud| %>
  <p> First Name : <%= crud.f_name %></p>
  <p> Last Name : <%= crud.l_name %></p>
  <%= link_to "show", crud_path(crud) %>
  <%= link_to "edit", edit_crud_path(crud) %>
  <%= link_to "delete", crud_path(crud), method: :delete %>
<% end %>

app/views/cruds/show.html.erb
<h1> Show </h1>

<p> First Name : <%= @crud.f_name %></p>
<p> Last Name : <%= @crud.l_name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CRUD</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>